print('TOKO MAINAN ANAK'.center(50))
print('******************'.center(50))
nama_pembeli= input('Masukkan nama pembeli  : ')
kode_mainan= input('Masukkan kode mainan   : ')
harga= input('Masukkan harga         : ')
jumlah_beli= input('Masukkan jumlah beli   : ')
total= (int(harga)*int(jumlah_beli))
print('===========================')
print('Nama Pembeli  :', nama_pembeli)
print('Kode Mainan   :', kode_mainan)
print('Harga         : Rp. ', harga)
print('Jumlah Beli   :', jumlah_beli)
print('Total         : Rp. ', total)